#include <errno.h>
#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "../git_ops.h"
#include "cmd.h"

/* ------------------------------------------------------------------ */
/* Helpers                                                              */
/* ------------------------------------------------------------------ */

static int mkdir_p(const char *path) {
  char tmp[1024];
  strncpy(tmp, path, sizeof(tmp) - 1);
  tmp[sizeof(tmp) - 1] = '\0';
  size_t len = strlen(tmp);
  if (len > 0 && tmp[len - 1] == '/')
    tmp[len - 1] = '\0';

  for (char *p = tmp + 1; *p; p++) {
    if (*p == '/') {
      *p = '\0';
      mkdir(tmp, 0755);
      *p = '/';
    }
  }
  return mkdir(tmp, 0755);
}

/* Write a manifest.xml wrapper that includes the real manifest */
static int write_manifest_link(const char *repodir, const char *manifest_name) {
  char path[1500];
  snprintf(path, sizeof(path), "%s/manifest.xml", repodir);

  FILE *fp = fopen(path, "w");
  if (!fp) {
    fprintf(stderr, "rpp init: cannot write %s: %s\n", path, strerror(errno));
    return -1;
  }
  fprintf(fp,
          "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
          "<!--\n"
          "  DO NOT EDIT THIS FILE!  It is generated by repo and changes will "
          "be discarded.\n"
          "  Use rpp init -m <file> to choose a different manifest.\n"
          "-->\n"
          "<manifest>\n"
          "  <include name=\"%s\" />\n"
          "</manifest>\n",
          manifest_name);
  fclose(fp);
  return 0;
}

/* ------------------------------------------------------------------ */
/* Public API                                                           */
/* ------------------------------------------------------------------ */

void cmd_init_usage(void) {
  printf("usage: rpp init -u <url> [-b <branch>] [-m <manifest>] [-g "
         "<groups>]\n");
}

void cmd_init_help(void) {
  cmd_init_usage();
  printf(
      "\nInitializes a rpp client checkout in the current directory.\n\n"
      "Options:\n"
      "  -u, --manifest-url URL    manifest repository URL (required)\n"
      "  -b, --manifest-branch B   manifest branch or revision (default: "
      "HEAD)\n"
      "  -m, --manifest-name FILE  manifest file name (default: default.xml)\n"
      "  -g, --groups G            restrict manifest projects to ones with "
      "specified group(s)\n"
      "  -q, --quiet               suppress output\n"
      "  --depth N                 shallow clone depth\n");
}

int cmd_init_run(CmdContext *ctx, int argc, char **argv) {
  (void)ctx;

  const char *manifest_url = NULL;
  const char *manifest_branch = NULL;
  const char *manifest_name = "default.xml";
  const char *manifest_groups = "default";
  int depth = 0;
  int quiet = 0;

  static struct option long_opts[] = {
      {"manifest-url", required_argument, NULL, 'u'},
      {"manifest-branch", required_argument, NULL, 'b'},
      {"manifest-name", required_argument, NULL, 'm'},
      {"groups", required_argument, NULL, 'g'},
      {"quiet", no_argument, NULL, 'q'},
      {"depth", required_argument, NULL, 'd'},
      {NULL, 0, NULL, 0}};

  int opt;
  optind = 1;
  while ((opt = getopt_long(argc, argv, "u:b:m:g:qd:", long_opts, NULL)) !=
         -1) {
    switch (opt) {
    case 'u':
      manifest_url = optarg;
      break;
    case 'b':
      manifest_branch = optarg;
      break;
    case 'm':
      manifest_name = optarg;
      break;
    case 'g':
      manifest_groups = optarg;
      break;
    case 'q':
      quiet = 1;
      break;
    case 'd':
      depth = atoi(optarg);
      break;
    default:
      cmd_init_usage();
      return 1;
    }
  }

  /* Positional argument as manifest URL */
  if (!manifest_url && optind < argc)
    manifest_url = argv[optind++];

  if (!manifest_url) {
    fprintf(stderr, "rpp init: --manifest-url is required\n");
    cmd_init_usage();
    return 1;
  }

  /* Determine repodir */
  char cwd[1024];
  if (!getcwd(cwd, sizeof(cwd))) {
    perror("getcwd");
    return 1;
  }

  char repodir[1200];
  snprintf(repodir, sizeof(repodir), "%s/.repo", cwd);

  /* Create directory structure */
  char manifests_dir[1300];
  char projects_dir[1300];
  snprintf(manifests_dir, sizeof(manifests_dir), "%s/manifests", repodir);
  snprintf(projects_dir, sizeof(projects_dir), "%s/projects", repodir);

  mkdir_p(repodir);
  mkdir_p(projects_dir);

  /* Clone or update the manifest repository.
   * "valid" means manifests/.git/config exists (a real git repo). */
  char git_config_path[1400];
  snprintf(git_config_path, sizeof(git_config_path), "%s/.git/config",
           manifests_dir);
  struct stat st, gitcfg_st;
  int is_valid_clone = (stat(git_config_path, &gitcfg_st) == 0);

  if (!is_valid_clone) {
    /* Remove any partial directory before cloning */
    if (stat(manifests_dir, &st) == 0) {
      char rm_cmd[2500];
      snprintf(rm_cmd, sizeof(rm_cmd), "rm -rf '%s'", manifests_dir);
      int ret = system(rm_cmd);
      (void)ret;
    }

    if (!quiet)
      printf("Cloning manifest repository from %s ...\n", manifest_url);

    GitCloneOpts opts = {
        .depth = depth,
        .branch = manifest_branch,
        .quiet = quiet,
    };
    if (git_clone(manifest_url, manifests_dir, &opts) != 0) {
      fprintf(stderr, "rpp init: failed to clone manifest from %s\n",
              manifest_url);
      return 1;
    }

    /* After clone, ensure we have the working tree checked out.
     * Needed when the remote's HEAD points to a nonexistent ref. */
    {
      const char *target = manifest_branch ? manifest_branch : "main";
      char origin_target[512];
      snprintf(origin_target, sizeof(origin_target), "origin/%s", target);
      /* Try to create and checkout the local tracking branch */
      const char *chk_args[] = {"checkout", "-b",          target,
                                "--track",  origin_target, NULL};
      /* Ignore errors - maybe it's already checked out */
      git_run(manifests_dir, chk_args, NULL, NULL);
    }
  } else {
    if (!quiet)
      printf("Updating manifest repository ...\n");

    if (git_fetch(manifests_dir, "origin", NULL, 1, depth) != 0) {
      fprintf(stderr, "rpp init: warning: failed to fetch manifest updates\n");
    }

    /* Checkout to ensure working tree is current */
    const char *target = manifest_branch ? manifest_branch : "main";
    char origin_target[512];
    snprintf(origin_target, sizeof(origin_target), "origin/%s", target);
    git_checkout(manifests_dir, origin_target);
  }

  /* Write .repo/manifest.xml */
  if (write_manifest_link(repodir, manifest_name) != 0)
    return 1;

  /* Save groups into .repo/manifests/.git/config for manifest_load to read */
  git_config_set(manifests_dir, "manifest.groups", manifest_groups);

  if (!quiet) {
    printf("\nrpp has been initialized in %s\n", cwd);
    printf("If this is not the directory in which you want to initialize repo, "
           "please run:\n");
    printf("   rm -r %s/.repo\nand try again.\n", cwd);
  }

  return 0;
}
