#include "cmd.h"
#include <stdio.h>

/* Package version comes from config.h (generated by autotools) */
#ifdef HAVE_CONFIG_H
#include "config.h"
#else
#define PACKAGE_VERSION "0.1.0"
#endif

/* ------------------------------------------------------------------ */
/* help                                                                 */
/* ------------------------------------------------------------------ */

void cmd_help_usage(void) { printf("usage: rpp help [<command>]\n"); }

void cmd_help_help(void) {
  cmd_help_usage();
  printf("\nDisplay help information about repo commands.\n");
}

int cmd_help_run(CmdContext *ctx, int argc, char **argv) {
  (void)ctx;
  if (argc >= 2) {
    const SubCommand *sc = cmd_find(argv[1]);
    if (!sc) {
      fprintf(stderr, "rpp: '%s' is not a rpp command.  See .rpp help..\n",
              argv[1]);
      return 1;
    }
    sc->help();
    return 0;
  }
  cmd_print_help(0);
  return 0;
}

/* ------------------------------------------------------------------ */
/* version                                                              */
/* ------------------------------------------------------------------ */

void cmd_version_usage(void) { printf("usage: rpp version\n"); }

void cmd_version_help(void) {
  cmd_version_usage();
  printf("\nDisplay the version of repo.\n");
}

int cmd_version_run(CmdContext *ctx, int argc, char **argv) {
  (void)ctx;
  (void)argc;
  (void)argv;
  printf("rpp version %s\n", PACKAGE_VERSION);
  printf("(C reimplementation of the Android repo tool)\n");
  return 0;
}
